keys:
  # Personal master key (passphrase-protected id_mothership.age)
  - &joni age1798uc9a5r3f8lsg0utsl5nsflnmrr6d0p6tqhpweldq2j9dftgmqgvjdln

  # Machine host keys (derived from SSH host key)
  - &mothership age13m0dh0996244ktl8qq8lst7q9ektpn544rz9fh7n86qnfxu8w3sq830mwa
  - &t480 age1jxuuk95fu7jdugytulhacehukgj0meyamyv5q4zwv6cfx2yyacjquj6cax

  # k3s fleet — carriers (control plane) and interceptors (workers)
  - &carrier-tc1 age1kafwpfpqdgq20w9s72xeqrrtxxlgg6ny3c8e0a0eytmecaw66f0sgwvx9f
  - &carrier-tc2 age1cwjmfd54hygcgeute8kcff62azxas5vv6ryt06jpucmcg0t7yvgqqlsmxf
  - &interceptor-nuc1 age10u3d2gjvmchtd4fphuk7m9dysmxg99xzxh9rye7t076zqu7r5ewsjvez4h
  - &interceptor-tc1 age1tr9z24jg6zy2mqfqppcahznn9acg6xp70nnlpmeenjw0q6v2hflqrekat2
  - &interceptor-tc2 age1v0ndd8prf9al0gj3sf269az2chzc76l53t38ngn9cu5796gtaurs7pwmht

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *joni
          - *mothership
          - *t480
          - *carrier-tc1
          - *carrier-tc2
          - *interceptor-nuc1
          - *interceptor-tc1
          - *interceptor-tc2
