# Locale settings
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

ssh_session() {
	if [ -z "$SSH_AUTH_SOCK" ]; then
	  eval $(ssh-agent -s)
	fi

	if ! ssh-add -l &>/dev/null; then
    	  ssh-add ~/.ssh/id_ecdsa &>/dev/null
	fi
}


cat () {
 bat --style plain --pager never "$@"
}

# Add Cargo and custom paths
export PATH="$HOME/.cargo/bin:$PATH"
export ZSH="$HOME/.oh-my-zsh"



HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
unsetopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
unsetopt HIST_SAVE_NO_DUPS
unsetopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY
HIST_STAMPS="mm/dd/yyyy"
# Share history
setopt SHARE_HISTORY
fpath=(~/.zsh/completion $fpath)

# Zsh plugins
#plugins=(git argocd aws battery brew catimg docker colorize colored-man-pages cp history iterm2 kubectl podman postgres qrcode redis-cli rust scala spring sudo terraform xcode zoxide)

# Zsh theme
#ZSH_THEME="powerlevel10k/powerlevel10k"

# SSH Keychain management - Ensure the key is added automatically on startup
eval `keychain --eval --quiet --quick --noask  --timeout 240 ~/.ssh/id_ecdsa`

# Finder function to open Finder from terminal
finder() {
  if [ -z "$1" ]; then
    # If no argument is passed, open Finder in the current directory
    open -a "Finder" .
  else
    # If a path is provided, open Finder at that path
    open -a "Finder" "$1"
  fi
}
dolphin () {
   finder "$*"
}

ssh () {
  ssh_session
  command ssh -X -CY -o ServerAliveInterval=120 $*
}
scp () {
   ssh_session
   command scp -C -v -r -o StrictHostKeyChecking=no $*
}
git () {
   ssh_session
   command git $*
}


# Source Oh-My-Zsh
source $ZSH/oh-my-zsh.sh

# Set architecture flags
export ARCHFLAGS="-arch $(uname -m)"



# Load Powerlevel10k theme if available
#[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# SDKMAN setup
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
source $HOME/.sdkman/bin/sdkman-init.sh

alias l='eza --icons'
alias la='eza --icons -a'
alias ll='eza --icons -lah'
alias ls='eza --icons --color=auto'

#remote
alias sw_debian='ssh -J bastion@51.158.121.209:61000 root@172.16.16.5'
alias sw_ubuntu='ssh -J bastion@51.15.132.29:61000 root@172.16.4.2'

bindkey "^[[3~" delete-char
bindkey "^[[5~" beginning-of-buffer-or-history
bindkey "^[[6~" end-of-buffer-or-history
bindkey -M emacs '^[[3;5~' kill-word
bindkey '^H' backward-kill-word
bindkey  "^[[3~"  delete-char
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word
bindkey '^[[1~' beginning-of-line
bindkey '^[[4~' end-of-line



