# /etc/rancher/rke2/manifests/letsencrypt-issuers.yaml

# --- Staging Issuer (for testing) ---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: jonathan@szigethy.dk
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-staging-private-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          # This class must match the class of your ingress controller.
          # The default for RKE2 is 'nginx'.
          class: nginx
---
# --- Production Issuer (for real certificates) ---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # You must replace this email address with your own.
    email: jonathan@szigethy.dk
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-production-private-key
    solvers:
    - http01:
        ingress:
          class: nginx
